[package]
name = "xde-sandbox-macro"
version = "0.0.1"
authors = ["stan <stanislav@yarmonov.pro>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
syn = { version = "1.0.11", features = ["full", "extra-traits"] }
proc-macro2 = "1.0.6"
quote = "1.0.2"
xde-sandbox = { path = "../sandbox" }
